### ISSUE TITLE
Switch between databases in Rails

### ISSUE THREAD

**Issue by bikashdey** [bikashdey/rails-task-notes#15]

**Comment by bikashdey** [comment]
Establishes the connection to the database. Accepts a hash as input where the :adapter key must be specified with the name of a database adapter (in lower-case) example for regular databases (MySQL, PostgreSQL, etc):


```
ActiveRecord::Base.establish_connection(
  adapter:  "mysql2",
  host:     "localhost",
  username: "myuser",
  password: "mypass",
  database: "somedatabase"
)
```

**Comment by bikashdey** [comment]
If we have multiple database and one main database, and want to fetch data from multiple database then we use activerecord establish connection.
eg:- main db_name = rails_api_development
       another db_name =rails_api_establish_development

main db we have user_details(email,password,username) and another db_name we have articles details.

1) Now for main database :- config/database.yml

```
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  host: localhost

development:
  <<: *default
  database: rails_api_development

```

2) Now we want to use another database to fetch data of articles..

app/controller/articles_controller
```
class ArticlesController < ApplicationController

    before_action :set_connection

    def index

        articles = Article.all

        render json: articles

    end

    def create
     
        article = Article.new(article_params)
        article.save

    end



    def show

        article = Article.find(params[:id])

        render json: article

    end
  

    def update
    
        article = Article.find(params[:id])
        article.article_name = params[:article][:article_name]
        article.article_description = params[:article][:article_description]

        if article.save
            render json: article
        else

            render json: { status: 400 , message: "article updated successfully" }
        end 

    end

    def destroy
        article = Article.find(params[:id])
        article.destroy

        render json: {status: 200 , message: "article destroyed successfully.."}
    end

    private

    
    def article_params
        params.require(:article).permit(:article_name, :article_description)
    end

    def set_connection
        ActiveRecord::Base.establish_connection(
            adapter:  "mysql2",
            host:     "localhost",
            username: "root",
            password: "",
            database: "rails_api_establish_development"
          )
    
    end

end
```

**Comment by bikashdey** [comment]
Now for main database :- config/database.yml

```
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  host: localhost

development:
  <<: *default
  database: rails_api_development

```

app/controller/articles_controller

```

class ArticlesController < ApplicationController
    before_action :set_connection

    def index

        articles = Article.all

        render json: articles

    end

    def create
     
        article = Article.new(article_params)
        article.save

    end



    def show

        article = Article.find(params[:id])

        render json: article

    end
  

    def update
   
        article = Article.find_by(params[:id])
        article.article_name = params[:article][:article_name]
        article.article_description = params[:article][:article_description]

        if article.save
            render json: article
        else

            render json: { status: 400 }
        end 

    end

    def destroy
        article = Article.find_by(params[:id])
        article.destroy

        render json: {status: 200 , message: "article destroyed successfully.."}
    end

    private

    
    def article_params
        params.require(:article).permit(:article_name, :article_description)
    end

    def set_connection
        ActiveRecord::Base.clear_active_connections!
        ActiveRecord::Base.establish_connection(
            adapter:  "mysql2",
            host:     "localhost",
            username: "root",
            password: "",
            database: "rails_api_development"
          )
    
    end

end
```


url:- http://127.0.0.1:3000/articles/

![Screenshot (86)](https://user-images.githubusercontent.com/74043649/142178868-243f2d24-e873-4f98-aef9-f1ea9d986bc5.png)
